//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tarjeta_Credito
    {
        [Required]
        [Display(Name = "Número de Tarjeta:")]
        public int Numero_Tarjeta { get; set; }
        [Required]
        [Display(Name = "CVC:")]
        public int CVC { get; set; }
        [Required]
        [Display(Name = "Fecha Caducidad:")]
        public System.DateTime Fecha_Caducidad { get; set; }
        

        public virtual Clientes Clientes { get; set; }
    }
}
